#### 3D Celestial Body mechanics in Python
### Steps
- Create class that defines a body

In [4]:
class body_v1:
    def __init__(self, mass, pos, vel, acc, force, index):
        self.mass = mass
        self.pos = pos
        self.vel = vel
        self.acc = acc
        self.force = force
        self.index = index

Now we make the bodies and add them to a list

In [114]:
import numpy
import matplotlib.animation as animation
from IPython.display import HTML
import matplotlib.pyplot as plt

deltaTime = 0.1

List_V1 = []

for i in range(10):
    List_V1.append(body_v1(mass = 10, pos = numpy.array([0,0,0]), vel = numpy.array([0,0,0]), acc = numpy.array([0,0,0]), force = numpy.array([0,0,0]), index = i))

In [6]:
def Interaction_Stiffness():
    for body in List_V1:
        pass

In [7]:
#%%timeit

def Interaction_Stiffness(List):
    for body1 in List:
        for body2 in List[body1.index + 1:]:
            #print(body1.index,body2.index)
            pass
def Interaction_Stiffness_enumerate(List):
    for index, body1 in enumerate(List):
        for body2 in List[index + 1:]:
            #print(body1.index,body2.index)
            pass

#Interaction_Stiffness(List)

In [8]:
class body_v2:
    def __init__(self, mass, pos, vel, acc, force, index):
        self.mass = mass
        self.pos = pos
        self.vel = vel
        self.acc = acc
        self.force = force
        self.index = index
    def Update_acc(self):
        self.acc = self.force/self.mass

def Interaction_Force(List):
    grav_const = 6.674e-11
    for body1 in List:
        for body2 in List[body1.index + 1:]:
            distance = body2.pos - body1.pos
            magnitude = abs(distance)
            BodyForces = (grav_const*body1.mass*body2.mass*distance)/numpy.power(magnitude, 3)
            body1.force = body1.force + BodyForces
            body2.force = body2.force - BodyForces
            pass

In [9]:
List_V2 = []

for i in range(10):
    List_V2.append(body_v2( mass = 10, pos = numpy.double([i,i,i]), vel = numpy.double([0,0,0]), acc = numpy.double([0,0,0]), force = numpy.double([0,0,0]), index = i))

Interaction_Force(List_V2)

In [10]:
class body_v3:
    def __init__(self, mass, pos, vel, acc, force, index):
        self.mass = mass
        self.pos = pos
        self.vel = vel
        self.acc = acc
        self.force = force
        self.index = index
    def Update_acc(self):
        self.acc = self.force/self.mass
    def Update_vel(self):
        self.vel = self.vel + self.acc * deltaTime
    def Update_pos(self):
        self.pos = self.pos + self.vel * deltaTime
    def Reset_force(self):
        self.force = numpy.double([0,0,0])

In [11]:
def Start(List):
    for i in range(10):
        List.append(body_v3(mass = 10, pos = numpy.double([i,i,i]), vel = numpy.double([0,0,0]), acc = numpy.double([0,0,0]), force = numpy.double([0,0,0]), index = i))
def Update(List):
    Interaction_Force(List)
    for body_n in List:
        body_n.Update_acc()
        body_n.Update_vel()
        body_n.Update_pos()
        body_n.Reset_force()


In [133]:
List_V3 = []
Start(List_V3)
for i in range(10):
    Update(List_V3)

array([0., 0., 0.])

array([1., 1., 1.])

array([2., 2., 2.])

array([3., 3., 3.])

array([4., 4., 4.])

array([5., 5., 5.])

array([6., 6., 6.])

array([7., 7., 7.])

array([8., 8., 8.])

array([9., 9., 9.])

array([1.977696e-12, 1.977696e-12, 1.977696e-12])

array([1., 1., 1.])

array([2., 2., 2.])

array([3., 3., 3.])

array([4., 4., 4.])

array([5., 5., 5.])

array([6., 6., 6.])

array([7., 7., 7.])

array([8., 8., 8.])

array([9., 9., 9.])

array([5.93308799e-12, 5.93308799e-12, 5.93308799e-12])

array([1., 1., 1.])

array([2., 2., 2.])

array([3., 3., 3.])

array([4., 4., 4.])

array([5., 5., 5.])

array([6., 6., 6.])

array([7., 7., 7.])

array([8., 8., 8.])

array([9., 9., 9.])

array([1.1866176e-11, 1.1866176e-11, 1.1866176e-11])

array([1., 1., 1.])

array([2., 2., 2.])

array([3., 3., 3.])

array([4., 4., 4.])

array([5., 5., 5.])

array([6., 6., 6.])

array([7., 7., 7.])

array([8., 8., 8.])

array([9., 9., 9.])

array([1.977696e-11, 1.977696e-11, 1.977696e-11])

array([1., 1., 1.])

array([2., 2., 2.])

array([3., 3., 3.])

array([4., 4., 4.])

array([5., 5., 5.])

array([6., 6., 6.])

array([7., 7., 7.])

array([8., 8., 8.])

array([9., 9., 9.])

array([2.96654399e-11, 2.96654399e-11, 2.96654399e-11])

array([1., 1., 1.])

array([2., 2., 2.])

array([3., 3., 3.])

array([4., 4., 4.])

array([5., 5., 5.])

array([6., 6., 6.])

array([7., 7., 7.])

array([8., 8., 8.])

array([9., 9., 9.])

array([4.15316159e-11, 4.15316159e-11, 4.15316159e-11])

array([1., 1., 1.])

array([2., 2., 2.])

array([3., 3., 3.])

array([4., 4., 4.])

array([5., 5., 5.])

array([6., 6., 6.])

array([7., 7., 7.])

array([8., 8., 8.])

array([9., 9., 9.])

array([5.53754879e-11, 5.53754879e-11, 5.53754879e-11])

array([1., 1., 1.])

array([2., 2., 2.])

array([3., 3., 3.])

array([4., 4., 4.])

array([5., 5., 5.])

array([6., 6., 6.])

array([7., 7., 7.])

array([8., 8., 8.])

array([9., 9., 9.])

array([7.11970558e-11, 7.11970558e-11, 7.11970558e-11])

array([1., 1., 1.])

array([2., 2., 2.])

array([3., 3., 3.])

array([4., 4., 4.])

array([5., 5., 5.])

array([6., 6., 6.])

array([7., 7., 7.])

array([8., 8., 8.])

array([9., 9., 9.])

array([8.89963198e-11, 8.89963198e-11, 8.89963198e-11])

array([1., 1., 1.])

array([2., 2., 2.])

array([3., 3., 3.])

array([4., 4., 4.])

array([5., 5., 5.])

array([6., 6., 6.])

array([7., 7., 7.])

array([8., 8., 8.])

array([9., 9., 9.])

In [131]:
class body_v4:
    def __init__(self, mass, radius, pos, vel, acc, force, index):
        self.mass = mass
        self.radius = radius
        self.pos = pos
        self.vel = vel
        self.acc = acc
        self.force = force
        self.index = index
    def Update_acc(self):
        self.acc = self.force/self.mass
    def Update_vel(self):
        self.vel = self.vel + self.acc * deltaTime
    def Update_pos(self):
        self.pos = self.pos + self.vel * deltaTime
    def Reset_force(self):
        self.force = numpy.double([0,0,0])

def Start(List):
    for i in range(10):
        List.append(body_v4(mass = 10, radius = 0.1, pos = numpy.double([i,i,i]), vel = numpy.double([0,0,0]), acc = numpy.double([0,0,0]), force = numpy.double([0,0,0]), index = i))
    return List

def verify_Distance(magnitude, distance, body1, body2):
    if (magnitude <= (body1.radius + body2.radius)):
        new_vel1 = body1.vel - ((2*body2.mass)/(body1.mass + body2.mass)) * ((numpy.dot((body1.vel-body2.vel),(-distance)))/numpy.power(magnitude, 2))*(-distance)
        new_vel2 = body2.vel - ((2*body1.mass)/(body1.mass + body2.mass)) * ((numpy.dot((body2.vel-body1.vel),(distance)))/numpy.power(magnitude, 2))*(distance)
        body1.vel = new_vel1
        body2.vel = new_vel2
    pass

def Interaction_Force(List):
    grav_const = 6.674e-11
    for body1 in List:
        for body2 in List[body1.index + 1:]:
            distance = body2.pos - body1.pos
            magnitude = numpy.sqrt(distance.dot(distance))
            verify_Distance(magnitude, distance, body1, body2)
            BodyForces = (grav_const*body1.mass*body2.mass*distance)/numpy.power(magnitude, 3)
            body1.force = body1.force + BodyForces
            body2.force = body2.force - BodyForces
            pass

In [121]:
List_V4 = []
Start(List_V4)
#Update(List_V4)

In [132]:
def Update(List):
    Interaction_Force(List)
    for body_n in List:
        display(body_n.pos)
        body_n.Update_acc()
        body_n.Update_vel()
        body_n.Update_pos()
        body_n.Reset_force()
    #return ax.plot(body.pos for body in List)


In [ ]:
from functools import partial

def UpdateFrame(frame,List,points):
    for body_n, point in zip(List, points):
        body_n.Update_acc()
        body_n.Update_vel()
        body_n.Update_pos()
        body_n.Reset_force()
        point = ax.plot([body_n.pos[0]],[body_n.pos[1]],[body_n.pos[2]],'o')[0]
        display(body_n.pos)
    return points

fig = plt.figure()
ax = fig.add_subplot(projection="3d")
points = [ax.plot([], [], [], 'o')[0] for _ in List_V4]

anim = animation.FuncAnimation(fig, partial(UpdateFrame, List = List_V4, points = points), frames = 100, interval=100)

plt.close(anim._fig)

HTML(anim.to_html5_video())